export enum YoutubeMusicTopic {
  All = "/m/04rlf",
  Christian = "/m/02mscn",
  Classical = "/m/0ggq0m",
  Country = "/m/01lyv",
  Electronic = "/m/02lkt",
  Hiphop = "/m/0glt670",
  Independent = "/m/05rwpb",
  Jazz = "/m/03_d0",
  Asian = "/m/028sqc",
  Latin = "/m/0g293",
  Pop = "/m/064t9",
  Reggae = " /m/06cqb",
  RhytmAndBlues = "/m/06j6l",
  Rock = "/m/06by7",
  Soul = "/m/0gywn",
}
